Repository SalesforceFoundation/OutboundFundsModuleNPSP, pull requests merged in 2022-05, with the labels that each got.

#76 W-8988843 Require Apex code coverage
  cumulusci.yml
Labels: Ready for QE, ready for RE review

#77 W-11125834 Bump dependencies
  package.json
  yarn.lock
Labels: Integrate

#78 W-11091826 Manage Expenditures Component
  force-app/main/default/lwc/manageExpenditures/manageExpenditures.js
  robot/OutboundFundsNPSP/doc/Keywords.html
  robot/OutboundFundsNPSP/resources/OutboundFundsNPSP.py
  robot/OutboundFundsNPSP/resources/locators_51.py
  robot/OutboundFundsNPSP/resources/locators_54.py
  robot/OutboundFundsNPSP/tests/browser/Requirements/Requirements.robot
  robot/OutboundFundsNPSP/tests/create_contact.robot
Labels: QE in Progress
